Task1 part2 implementation design
Mohsen-Awad/assignments pull request #2
Opened 2021-03-21 13:45 UTC by Mohsen-Awad

2021-03-21 20:52 UTC, ashrafabuodeh requested changes

2021-03-21 20:52 UTC, ashrafabuodeh commented on task_1/index.html
remove space here

2021-03-21 20:52 UTC, ashrafabuodeh commented on task_1/index.js
> +
remove space

2021-03-21 20:52 UTC, ashrafabuodeh commented on task_1/style.css
remove space

2021-03-21 23:35 UTC, araraltawarah98 approved these changes

2021-03-21 23:35 UTC, araraltawarah98 commented on task_1/index.html
> +                <div class="image2"><img src="MOcha Late 02.png" alt="MOCHA LATE"></div>
let img tag down div tag.

2021-03-22 07:19 UTC, abood454 requested changes

2021-03-22 07:19 UTC, abood454 commented on task_1/style.css
> -    margin-top: 20px;
use shorthand margin

2021-03-22 07:19 UTC, abood454 commented on task_1/index.js
> +
remove space

2021-03-22 23:08 UTC, ashrafabuodeh approved these changes

2021-03-23 00:32 UTC, araraltawarah98 approved these changes

2021-03-23 07:53 UTC, abood454 approved these changes

2021-03-23 07:55 UTC, araraltawarah98 approved these changes

2021-03-24 11:30 UTC, mmasaid commented on task_1/index.html
> +                <div><img class="coffee-image-logo" src="./photo/coffee logo.png" alt="coffee logo"></div>
use kabab case for image name, ids and class
```suggestion
                <div><img class="coffee-image-logo" src="./photo/coffee-logo.png" alt="coffee logo"></div>
```

2021-03-24 11:31 UTC, mmasaid commented on task_1/index.html
> +                <div><img class="shopping-image" src="./photo/shopping cart.png" alt="shopping cart"></div>
use kabab case for image name, ids and class

apply it everywhere 
```suggestion
                <div><img class="shopping-image" src="./photo/shopping-cart.png" alt="shopping cart"></div>
```

2021-03-24 11:32 UTC, mmasaid commented on task_1/index.html
> +                    <p class="first-title">Be Active</p>
```suggestion
                    <h4 class="item-main-title">Be Active</h4>
```

2021-03-24 11:33 UTC, mmasaid commented on task_1/index.html
> +                    <p class="third-title">Top Packs</p>
I think if you use sub-title will be better 
```suggestion
                    <h1 class="second-title">Barnsley Brew Coffee</h1>
                    <p class="second-title-p">Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain Coffea species. When coffee berries turn from.</p>
                    <p class="third-title">Top Packs</p>
```

2021-03-24 11:34 UTC, mmasaid commented on task_1/index.js
> +}
👍

2021-03-24 11:50 UTC, mmasaid commented on task_1/style.css
> +.distance {
```suggestion
.price-container {
```

2021-03-24 11:52 UTC, mmasaid requested changes
Please address the comments and let me know if you have any question

2021-03-24 14:15 UTC, mmasaid approved these changes
LGTM

2021-03-24 14:24 UTC, merged