Task1 part3 responsive design
Mohsen-Awad/assignments pull request #4
Opened 2021-03-29 07:01 UTC by Mohsen-Awad

2021-03-29 10:27 UTC, araraltawarah98 requested changes

2021-03-29 10:27 UTC, araraltawarah98 commented on .vscode/settings.json
> +}
add the end of the file line

2021-03-29 10:27 UTC, araraltawarah98 commented on task_1/photo/menu-icon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"/></svg>
add the end of the file line

2021-03-30 06:52 UTC, abood454 approved these changes

2021-03-30 06:53 UTC, araraltawarah98 approved these changes

2021-03-30 09:52 UTC, mmasaid commented on task_1/index.html
> +            <div class="navbar" id="navbar">
```suggestion
            <div class="navbar" id="menu-navbar">
```

2021-03-30 09:53 UTC, mmasaid commented on task_1/index.html
> +    <table id="employees"></table>
git ride this line no need for the table 
I think it was by mistake 
```suggestion
```

2021-03-30 09:53 UTC, mmasaid commented on task_1/index.js
> +
```suggestion
```

2021-03-30 09:54 UTC, mmasaid commented on task_1/index.js
> +    for (let i = 0; i < menu_items.length; i++)
```suggestion
    for (let i = 0; i < menu_items.length; i++){
    ...
    }
```

2021-03-30 09:54 UTC, mmasaid commented on task_1/index.js
> +
```suggestion
```

2021-03-30 09:55 UTC, mmasaid commented on task_1/index.js
> +    let menu_item = document.getElementById("navbar");
```suggestion
    let menu_item = document.getElementById("menu-navbar");  
```

2021-03-30 09:58 UTC, mmasaid commented on task_1/style.css
> +    justify-content: end;
```suggestion
    justify-content: flex-end;
```

2021-03-30 09:59 UTC, mmasaid commented on task_1/style.css
> +}
```suggestion
Alphabetize please 
.menu-icon{
    cursor: pointer;
    width: 50px;
    height: 50px;
    display: none;
    margin-top: 20px;
}
```

2021-03-30 10:01 UTC, mmasaid commented on task_1/style.css
> +        justify-content: flex-end;
Alphabetize please 
```suggestion
......
        flex-direction: column;
        visibility: hidden;
        justify-content: space-between;
        background-color:rgb(167, 184, 216);
        z-index: 1;
        margin-top: 370px;
        width: 100%;
        justify-content: flex-end;
```

2021-03-30 10:02 UTC, mmasaid commented on task_1/style.css
> +    .header{
line space between class 
Apply it in the whole file
```suggestion

    .header{
```

2021-03-31 08:11 UTC, merged